### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by marioaks** [gorhom/react-native-bottom-sheet#11]
Hey!

I just started using this, and so far it's great! Seems like the best bottom drawer out there

# Feature Request

I'm currently trying to use this library with an Expo / React Native Web app. In order to get it working, I used `patch-package` to add a `Touchables.web.js` file and a `ContentWrapper.web.js` file that are exact replicas of their respective ios files. I was wondering if it would be possible to add these two files so patching isn't necessary to support web?

Thanks!

**Comment by gorhom** [comment]
hi @marioaks , if you get it working for web ... well done !! 

please submit a pr and i'll merge it asap 😇

**Comment by nandorojo** [comment]
Hey there, just wondering if you think this will get merged? Thanks for the awesome work on this library, & @marioaks for identifying this issue.

**Comment by gorhom** [comment]
@nandorojo unfortunately i tested this pr, but it is not working properly and i was planning to pick it up but i didn't had the time for it. https://github.com/gorhom/react-native-bottom-sheet/pull/14

**Comment by nandorojo** [comment]
Sounds good, thanks for the heads up!

**Comment by nandorojo** [comment]
Just wondering, is there somewhere you think I should look if I want to try to get this to work on web? Files to change that need work, etc.

**Comment by gorhom** [comment]
hi @nandorojo, to be honest i am not an expert in `react-native-web`. however, you could pick @marioaks pr and i'll try my best to help out :)

**Comment by Angelk90** [comment]
@marioaks : Are there any news?

**Comment by marioaks** [comment]
The PR I submitted was a barebone patch for react-native-web but was never fully functioning. I should have submitted the PR as a draft since I still needed some guidance on how to proceed with the styling of the drawer on web. 

In other words, this PR was never in a mergeable state, but since I never received any sort of feedback on it, I wasn't able to move forward.

**Comment by Angelk90** [comment]
@marioaks : I think you should ask @gorhom.

**Comment by marioaks** [comment]
Hopefully the PR is useful for anyone who tries to get this working for RNW, but I no longer have the time to work on this. Sorry @Angelk90

**Comment by planecore** [comment]
Any updates on this? @gorhom

**Comment by zhigang1992** [comment]
@planecore this actually now works out of the box (almost) see #357 for more detail

**Comment by nandorojo** [comment]
How do you guys handle the UX on a large screen? I wonder if it should become a modal instead of a sheet on a large desktop. Or, do you just set a max width?

**Comment by gorhom** [comment]
thanks @zhigang1992 ❤️ , i will look at later today!

>How do you guys handle the UX on a large screen? I wonder if it should become a modal instead of a sheet on a large desktop. Or, do you just set a max width?

@nandorojo good idea, this is something @thupi also suggested but for tablets
https://github.com/gorhom/react-native-bottom-sheet/discussions/234

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by axeldelafosse** [comment]
Here is an example working with Expo and Next.js: https://github.com/axeldelafosse/bottom-sheet-example. I'll send a PR soon so we don't need to use [this patch](https://github.com/axeldelafosse/bottom-sheet-example/blob/main/patches/%40gorhom%2Bbottom-sheet%2B4.0.0-alpha.18.patch)

**Comment by ajturpei** [comment]
Any news on this? We are using this great bottom sheet but it causes gray hair with React-native-web even when you don't use it for RN web but you import this package in a file that RN web is using.

**Comment by nandorojo** [comment]
use the patch from this comment in the meantime https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-893502341

**Comment by gorhom** [comment]
@ajturpei @nandorojo @axeldelafosse , i have applied the patch to enable the current library to run on web on `4.0.0-alpha.27` 👍

**Comment by Angelk90** [comment]
@gorhom : Could you create an example on snack.expo.io to try out web support?

**Comment by JJK801** [comment]
Hi @gorhom,

i can't get it working on web, i get an error 

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at useDerivedValue (Hooks.js:432)
    at BottomSheet (BottomSheet.js:97)
```

Did i miss something to make it works ?

**Comment by nandorojo** [comment]
Try following these instructions, but replace moti with the bottom sheet:

https://moti.fyi/web

**Comment by nandorojo** [comment]
> @gorhom : Could you create an example on snack.expo.io to try out web support? 

Expo Snack uses a version of react-native-web that's incompatible with Reanimated 2. So unfortunately, it won't work well on a snack.

I tried to get reanimated 2 working on CodeSandbox, but I can't seem to figure out how. If someone could do that, it would be great.

**Comment by JJK801** [comment]
Thanks @nandorojo 👍 

For memory: 

`webpack.config.json`
```javascript
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
    const config = await createExpoWebpackConfigAsync(
        {
            ...env,
            babel: { dangerouslyAddModulePathsToTranspile: ['@gorhom'] },
        },
        argv
    );

    return config;
};
```

**Comment by nandorojo** [comment]
@gorhom I recommend adding that to the docs (and link to Axel’s monorepo for adding Next.js support).

**Comment by ngochnvn** [comment]
Hi @gorhom,

Is it possible to merge the web fix into v2? I upgraded to v4 and it seems to compile for web. However, I am not able to test on expo managed due because v4 uses reanimated2, so I have to downgrade to v2. 

Thank you very much

**Comment by Angelk90** [comment]
@gorhom : Could you create an example on snack.expo.io to try out web support?

**Comment by LinusU** [comment]
I don't think that this is stale, but it seems like this is already working. Could we get this added to the readme?

**Comment by Angelk90** [comment]
@gorhom : Could you create an example on snack.expo.io to try out web support?

**Comment by webdiller** [comment]
I found only 2 libs 'bottom-sheet' for web. It's 'react-modal-sheet' and 'react-spring-bottom-sheet'.

**Comment by Angelk90** [comment]
@gorhom : Could you create an example on snack.expo.io to try out web support?

**Comment by Joeao** [comment]
For Webpack users not using expo, you can tell babel-loader to deal with this project + reanimated as so:

```ts
// webpack.config.ts
module.exports = {
	...
	module: {
		rules: [
			{
				test: /\.js$/i,
				loader: "babel-loader",
				include: [
					path.resolve("node_modules/react-native-reanimated"),
					path.resolve("node_modules/@gorhom/bottom-sheet")
				]
			},
		]
	},
};

```

This should give the result as https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-916025454

**Comment by jeanniton-mnr** [comment]
The latest version of the BottomSheet has an issue relating to babel for the web version - not working at all. 
I have used v4 alpha.18 @ :   
https://www.npmjs.com/package/@gorhom/bottom-sheet/v/4.0.0-alpha.18

**Comment by Angelk90** [comment]
@gorhom : Could you create an example on snack.expo.io to try out web support?

**Comment by jeanniton-mnr** [comment]
> 

Thank you @JJK801, @axeldelafosse, and @gorhom .

These are the following steps that have worked for me:   

1. Install bottom-sheet version 4.0.0-alpha.18
> `npm i @gorhom/bottom-sheet@4.0.0-alpha.18`
   
   
2. Apply patch from @axeldelafosse :   

    2.1.1.  Install patch-packager module:
    > `npm i -D patch-package postinstall-postinstall`

    2.1.2. In `package.json`, add: 
    ```
    "scripts": {
    +  "postinstall": "patch-package"
    }
    ```
    
    2.1.3. Copy patch from @axeldelafosse [repo](https://github.com/axeldelafosse/bottom-sheet-example/blob/main/patches/%40gorhom%2Bbottom-sheet%2B4.0.0-alpha.18.patch); follow the same directory structure.
    

    2.2. Delete `./node_modules`
   
    2.3. Re-install node modules to apply patches:
    > `npm i`
   

3. Since we use Reanimated 2 on the web, we need its Babel plugin to be applied to BottomSheet. As Expo Web doesn't transpile modules by default, we'll need to tell it to transpile BottomSheet.

    3.1. Install _`expo/webpack-config`_:
    > `npm install -D @expo/webpack-config`
   
    3.2. Create _`webpack.config.js`_ on project root with the following content:
    ```
    const createExpoWebpackConfigAsync = require('@expo/webpack-config');
    
    module.exports = async function (env, argv) {
        const config = await createExpoWebpackConfigAsync(
            {
                ...env,
                babel: { dangerouslyAddModulePathsToTranspile: ['@gorhom'] },
            },
            argv
        );
    
        return config;
    };
    ```   

    3.3.  Re-run the project:
    > `expo start --web`
    

    
###     I hope you enjoyed the guide and it has worked for you too.

**Comment by vcebotari** [comment]
it not working in case of metro bundler

**Comment by jeanniton-mnr** [comment]
> it not working in case of metro bundler

What issue are you getting?    


If you need to transpile with Metro for Web, maybe you use the same syntax as [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer#step-3-configure-the-react-native-packager)

**Comment by LinusU** [comment]
It would be great to have web support mentioned in the readme, I can open a PR to add it under "Features"?

**Comment by Soft-Gurus** [comment]
what kind of changes are required to resolve this issue on expo?
I have metro.config.js file. And error is same when running on iOS device.

**Comment by jeanniton-mnr** [comment]
> 

I have not tested it on iOS yet. I also don't know what issue you are getting specifically.     

You can share your repo with me, or part of your project, and I will look at it for you.     

Best,

**Comment by vcebotari** [comment]
> 

for me the issue is what your config is for webpack, and it's incompatible with `metro.config.js`, my project is written on bare react native ( not web, not expo)

**Comment by jeanniton-mnr** [comment]
This solution should still work for you.

Have you tried to follow it step by step?

https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-1072756577

**Comment by LinusU** [comment]
> It would be great to have web support mentioned in the readme, I can open a PR to add it under "Features"?

@gorhom would you be open to this?

**Comment by LinusU** [comment]
not stale ☺️

**Comment by thatzacdavis** [comment]
@LinusU it probably wouldn't hurt to just submit a PR?

**Comment by EricBorland** [comment]
> > 
> 
> Thank you @JJK801, @axeldelafosse, and @gorhom .
> 
> These are the following steps that have worked for me:
> 
> 1. Install bottom-sheet version 4.0.0-alpha.18
> 
> > `npm i @gorhom/bottom-sheet@4.0.0-alpha.18`
> 
> 2. Apply patch from @axeldelafosse :
>    2.1.1.  Install patch-packager module:
>    > `npm i -D patch-package postinstall-postinstall`
>    
>    
>    2.1.2. In `package.json`, add:
>    ```
>    "scripts": {
>    +  "postinstall": "patch-package"
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    2.1.3. Copy patch from @axeldelafosse [repo](https://github.com/axeldelafosse/bottom-sheet-example/blob/main/patches/%40gorhom%2Bbottom-sheet%2B4.0.0-alpha.18.patch); follow the same directory structure.
>    2.2. Delete `./node_modules`
>    2.3. Re-install node modules to apply patches:
>    > `npm i`
> 3. Since we use Reanimated 2 on the web, we need its Babel plugin to be applied to BottomSheet. As Expo Web doesn't transpile modules by default, we'll need to tell it to transpile BottomSheet.
>    3.1. Install _`expo/webpack-config`_:
>    > `npm install -D @expo/webpack-config`
>    
>    
>    3.2. Create _`webpack.config.js`_ on project root with the following content:
>    ```
>    const createExpoWebpackConfigAsync = require('@expo/webpack-config');
>    
>    module.exports = async function (env, argv) {
>        const config = await createExpoWebpackConfigAsync(
>            {
>                ...env,
>                babel: { dangerouslyAddModulePathsToTranspile: ['@gorhom'] },
>            },
>            argv
>        );
>    
>        return config;
>    };
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    3.3.  Re-run the project:
>    > `expo start --web`
> 
> ### I hope you enjoyed the guide and it has worked for you too.

While this work for most of it, I have the following issue when using the BottomSheetScrollView

```
Uncaught Error: Unexpected nativeTag: function; nativeTag=[object HTMLDivElement] 

			createBottomSheetScrollableComponent's ScrollableComponent needs to return 
			a reference that contains a nativeTag to a Native HostComponent.

			ref=function _f(component) {
        if (component) {
          tag.value = Object(_NativeMethods__WEBPACK_IMPORTED_MODULE_1__["getTag"])(component);
          fun.current = component;
        }
        return tag.value;
      }
			
    at getRefNativeTag (getRefNativeTag.ts:31:1)
    at useScrollableSetter.ts:34:1
    at commitHookEffectListMount (react-dom.development.js:22969:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24707:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24666:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24653:1)
    at commitPassiveMountEffects (react-dom.development.js:24641:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26848:1)
    at flushPassiveEffects (react-dom.development.js:26801:1)
    at react-dom.development.js:26597:1
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
    at onGlobalMessage (setImmediate.js:109:1)
```

I'm not very experienced in React Native world and I'm not sure how to fix that, anyone willing to help on patching that?

Thanks.

**Comment by EricBorland** [comment]
^^^ I was able to workaround it using ScrollView in web platform instead. Not sure it's the best approach, but works by now:

1. Created a bottom-sheet-scroll-view.js and bottom-sheet-scroll-view.web.js files
2. The first one imports and exports the original BottomSheetScrollView from this repo
3. The second one just exports ScrollView as BottomSheetScrollView
4. Changed the import in all places where I was using the BottomSheetScrollView to import form _my_ "bottom-sheet-scroll-view" component

Just in case someone needs something like that while the actual fix is not implemented

**Comment by syahbes** [comment]
> Try following these instructions, but replace moti with the bottom sheet:
> 
> https://moti.fyi/web

Thanks !! that fixed my issue
(the bottom sheet worked only on the expo app and not on web)

**Comment by bombillazo** [comment]
Started working on a project using this library and Solito (coincidentally @nandorojo the creator is here).

I agree a modal probably be the appropriate component to render on web, but I don't see any guide on how to use it with web (using Next.js + RN). 

Any way to get it to work currently?

**Comment by likeSo** [comment]
> > > 
> > 
> > 
> > Thank you @JJK801, @axeldelafosse, and @gorhom .
> > These are the following steps that have worked for me:
> > 
> > 1. Install bottom-sheet version 4.0.0-alpha.18
> > 
> > > `npm i @gorhom/bottom-sheet@4.0.0-alpha.18`
> > 
> > 
> > 
> > 2. Apply patch from @axeldelafosse :
> >    2.1.1.  Install patch-packager module:
> >    > `npm i -D patch-package postinstall-postinstall`
> >    
> >    
> >    2.1.2. In `package.json`, add:
> >    ```
> >    "scripts": {
> >    +  "postinstall": "patch-package"
> >    }
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    2.1.3. Copy patch from @axeldelafosse [repo](https://github.com/axeldelafosse/bottom-sheet-example/blob/main/patches/%40gorhom%2Bbottom-sheet%2B4.0.0-alpha.18.patch); follow the same directory structure.
> >    2.2. Delete `./node_modules`
> >    2.3. Re-install node modules to apply patches:
> >    > `npm i`
> > 3. Since we use Reanimated 2 on the web, we need its Babel plugin to be applied to BottomSheet. As Expo Web doesn't transpile modules by default, we'll need to tell it to transpile BottomSheet.
> >    3.1. Install _`expo/webpack-config`_:
> >    > `npm install -D @expo/webpack-config`
> >    
> >    
> >    3.2. Create _`webpack.config.js`_ on project root with the following content:
> >    ```
> >    const createExpoWebpackConfigAsync = require('@expo/webpack-config');
> >    
> >    module.exports = async function (env, argv) {
> >        const config = await createExpoWebpackConfigAsync(
> >            {
> >                ...env,
> >                babel: { dangerouslyAddModulePathsToTranspile: ['@gorhom'] },
> >            },
> >            argv
> >        );
> >    
> >        return config;
> >    };
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    3.3.  Re-run the project:
> >    > `expo start --web`
> > 
> > ### I hope you enjoyed the guide and it has worked for you too.
> 
> While this work for most of it, I have the following issue when using the BottomSheetScrollView
> 
> ```
> Uncaught Error: Unexpected nativeTag: function; nativeTag=[object HTMLDivElement] 
> 
> 			createBottomSheetScrollableComponent's ScrollableComponent needs to return 
> 			a reference that contains a nativeTag to a Native HostComponent.
> 
> 			ref=function _f(component) {
>         if (component) {
>           tag.value = Object(_NativeMethods__WEBPACK_IMPORTED_MODULE_1__["getTag"])(component);
>           fun.current = component;
>         }
>         return tag.value;
>       }
> 			
>     at getRefNativeTag (getRefNativeTag.ts:31:1)
>     at useScrollableSetter.ts:34:1
>     at commitHookEffectListMount (react-dom.development.js:22969:1)
>     at commitPassiveMountOnFiber (react-dom.development.js:24707:1)
>     at commitPassiveMountEffects_complete (react-dom.development.js:24666:1)
>     at commitPassiveMountEffects_begin (react-dom.development.js:24653:1)
>     at commitPassiveMountEffects (react-dom.development.js:24641:1)
>     at flushPassiveEffectsImpl (react-dom.development.js:26848:1)
>     at flushPassiveEffects (react-dom.development.js:26801:1)
>     at react-dom.development.js:26597:1
>     at workLoop (scheduler.development.js:266:1)
>     at flushWork (scheduler.development.js:239:1)
>     at performWorkUntilDeadline (scheduler.development.js:533:1)
>     at run (setImmediate.js:40:1)
>     at runIfPresent (setImmediate.js:69:1)
>     at onGlobalMessage (setImmediate.js:109:1)
> ```
> 
> I'm not very experienced in React Native world and I'm not sure how to fix that, anyone willing to help on patching that?
> 
> Thanks.

Got this problem too: 
```
getRefNativeTag.js:27 Uncaught Error: Unexpected nativeTag: function; nativeTag=[object HTMLDivElement] 

			createBottomSheetScrollableComponent's ScrollableComponent needs to return 
			a reference that contains a nativeTag to a Native HostComponent.

			ref=function _f(component) {
          if (component) {
            tag.value = (0, _NativeMethods.getTag)(component);
            fun.current = component;
          }
          return tag.value;
        }
```
I am using the latest version 4.4.5
I just put a `BottomSheetFlatList` in a `BottomSheet` on the `react-native-web`

**Comment by waleedshkt** [comment]
If going for gesture-enabled bottom sheet on the web, then I would recommend [React Spring Bottom Sheet ](https://react-spring.bottom-sheet.dev/)

**Comment by bombillazo** [comment]
@waleedshkt thats exactly what we did

**Comment by giaset** [comment]
```
import { ScrollView, StyleSheet } from 'react-native';

import { BottomSheetScrollView } from '@gorhom/bottom-sheet';

const YourComponent = () => {
  const Container = IS_WEB ? ScrollView : BottomSheetScrollView;
  return (
    <Container contentContainerStyle={styles.contentContainer} style={styles.container}>
      {content}
    </Container>
  );
};
```

**Comment by PrajTS** [comment]
Can someone please help me with using gorhom bottomsheet on solito?

**Comment by maxshulov** [comment]
@PrajTS @bombillazo  same question here, I asked @nandorojo on the Discord channel waiting for his answer, because it looks like he made it work.

**Comment by maxshulov** [comment]
[Release 5.0.0-alpha.0](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v5.0.0-alpha.0) added support for web, all version after it work on my Solito app.
